### ISSUE TITLE
Initial server address cannot have trailing slash

### ISSUE THREAD

**Issue by daj102** [dough10/PolySonic#26]
Just installed PolySonic and tried to connect to my server.  However, when I entered my server address with a trailing slash:

http://the-johnstons.homenet.org:8080/

and my username/password, I got a small window that said [object Object] and nothing else happened.  I can repeatedly press Submit and I keep getting that same thing.  However, when I removed the trailing slash:

http://the-johnstons.homenet.org:8080

as per the example, I get a small window that says Loading data and away I go.

So action is basically to parse the server URL in a more robust manner ... :-)

**Comment by dough10** [comment]
thanks for the feed back. i will look into this issue.

**Comment by daj102** [comment]
:-)  thank you - awesome job :-)
