### ISSUE TITLE
Very nice app! It would be great if it is executable in all actual browsers.

### ISSUE THREAD

**Issue by gbreeze** [dough10/PolySonic#34]

**Comment by dough10** [comment]
there are a couple issues with this app working in browsers.

1. app is made with Polymer 0.5. Polymer 0.5 has performance issues on some browsers that do not natively support shadow dom. (a Polymer 1.0 version has been started but is VERY far away from being ready to use)

2. in a browser caching of art and metadata wouldn't work in the same way it does now. most browsers cap indexeddb (method used for caching art / metadata) at 50mb. while that is a lot of art and metadata a large library will use it up easily leaving the app broken when it tries to add more.

3. performance. the app runs in a small window cause there are performance issues with filling the screen with the album art elements used. as you scroll there are a lot of things that happen behind the scenes and in a attempt to keep scrolling close to 60 fps as i could i reduced the size of the player keeping as few elements on screen as i could. as i fix some of my bad code and performance gets better the possibility of being able to scale the app to cover fullscreen is closer but still not possible @ this time.

1 of the main perks of this app not being in a browser is offline first. if you are on lan with your subsonic server and have no internet the app can still work. if it were in browser and hosted on a server somewhere that wouldn't work without using a service worker / large local cache or something similar requiring https and making set up a real pain for end user.

so at this time i do not see a browser version happening. maybe after i get the Polymer 1.0 version farther along and see what performance looks like there.

thank you for the feedback and i hope you enjoy the app.
