### ISSUE TITLE
Request: podcast bookmarking/resume

### ISSUE THREAD

**Issue by williamkray** [dough10/PolySonic#39]
Projects like DSub for android (https://github.com/daneren2005/Subsonic) use Subsonic server to save bookmark podcast position data, so you can come back to the last part of the show you listened to. This would be a nice addition to polysonic, especially if it would be compatible with the same data, so your bookmark would be visible across programs.

I believe one example of how the DSub project defines bookmarks is here, but I'm not familiar enough with java/android apps to get more specific: https://github.com/daneren2005/Subsonic/blob/master/app/src/main/java/github/daneren2005/dsub/domain/Bookmark.java

**Comment by dough10** [comment]
This shouldn't be a issue to implement. Ill write a few functions and see how it looks. I think maybe do the buttons the same way as the repeat button in latest version. A bookmark icon on left side on player and also in the play queue options drop down.

**Comment by williamkray** [comment]
I've downloaded the 0.2.6 branch and have been playing with it to test, and this feature seems close but not fully realized yet. i'm not sure how involved it would be, but i think that if a file has a bookmark associated with it, there should be some sort of visual indicator next to the file (within queues or playlists, etc). that way, when selecting that file, you should have the option to either start from the beginning, or resume from the bookmark.

Also, when testing cross-application compatibility, the DSub app recognizes the bookmarks for the files correctly (i see them as an option) but i think they are recording and parsing times differently? when I create a bookmark in polysonic, and try to resume in DSub, Dsub starts the file playing at 0:00. i created a bookmark in DSub at 0:58 into a file, and resuming it in polysonic attempts playback at 980:48 (it's only a 20 minute podcast) so there's some differences in parsing the time there.

I have no idea which method of parsing time makes more sense, or if there's a standard, or if this is something that isn't worth trying to make work together. I don't know which other apps make use of the bookmarks feature.

It's definitely looking nice though, and much appreciated! if these work together, it means i could stop listening to a podcast in the car, and pick up where i left off when i get to my desk at work!

**Comment by dough10** [comment]
It can totally work. I see now where the issue is. The command asks for time in ms and I am sending seconds. When I get home I can fix pretty quick.  I am really glad you tested this. I almost posted last night. 

I think that if any file has a bookmark it will return that in all calls for info. If so I can add a bookmark icon next to the play icon for a file. Then bookmark would resume and play would start from beginning.  Does that sound good?

**Comment by williamkray** [comment]
awesome, i didn't realize the fix would be so simple!

that sounds just about perfect. that way, as you browse the files, you can
see "oh, this file has a bookmark" and just select "Resume from bookmark",
or selecting would just start playing from the beginning. The bookmarks
menu is nice, but unless you specifically name the bookmark with the file
that it's associated with, it might be hard to find exactly which bookmark
you want to select to resume the thing you're trying to play. having a
resume from bookmark option directly accessible from the file is simple and
straightforward.

let me know if you would like me to test, i've got the repo cloned as a
separate install in Chrome.

**Comment by dough10** [comment]
I have updated the repo. Bookmarks for podcast seem to work pretty well. I am still working on making it work on other files the same way. (indicator shows but no changes to button action at this moment) I am leaving the bookmark menu as is for the moment cause it is the only way to delete a bookmark. I was thinking about maybe making the indicator clickable and when clicked would show a delete confirmation dialog. I am still in the air on how to deal with deleting a bookmark. 

If you wanna check it out and let me know how you feel it works I would love the feedback.

**Comment by williamkray** [comment]
tested and confirmed, it works exactly as i would expect! fantastic stuff,
and impressive how quickly you were able to implement.

a clickable action on the bookmark icon is probably a good idea, though
having the bookmark menu is also reasonable. i suppose more ways to take
action on something means less confusion when someone wants to do the thing.

**Comment by dough10** [comment]
After looking at it this morning I can see that the bookmark indicator will need to be on the left side of the text. It isn't as big of a issue in podcast but on other files if the name is longer then the space the indicator would be hidden.

**Comment by williamkray** [comment]
Another thing I thought of but haven't tested is how resume handles
multiple bookmarks for the same file... I think maybe attempting to play
the file would show a pop up similar to the current dialog, but with a list
of start points in order of start time.

Multiple Bookmarks Found!

Start from beginning
Bookmark 1 (0:15)
Bookmark 2 (1:47)
Bookmark 3 (2:19)

I'm not sure how you're thinking of handling clicking on the bookmark icon,
but a pop-up menu that shows a similar interface to the bookmarks menu
makes sense. So clicking the icon shows all bookmarks for this file, with
the option to delete each one individually or delete all bookmarks for this
file.

--Sent from my mobile

**Comment by dough10** [comment]
I didn't know you could do more then one bookmark to a media file. API docs look like default behavior is to over write previous bookmark.

**Comment by williamkray** [comment]
Ah, then never mind :)

--Sent from my mobile

**Comment by dough10** [comment]
Before i attempt to complete this. I wanted to see how you felt about the current state of the feature? 
Does the clickable indicator work for you? I feel it doesn't really conveys it's purpose as a method to delete a bookmark. But at the same time i don't see many other options here. I thought maybe the click could open the bookmark menu. But that would only work if I set the default comment to be more descriptive of the file and location of the bookmark or if I filtered the results to only display the relevant bookmark to the file clicked. The only other really option I see is to have a tooltip show when hovering the indicator that tells the user it is a method to delete the bookmark. But that is another issues. The podcast page doesn't have tooltips at this time due to a strange scoping issue with nested Polymer templates. Maybe i am over thinking this.

**Comment by williamkray** [comment]
I see what you mean about it not being very intuitive to click on the
bookmark. Maybe if you made it a color, it would indicate that it's
something you can take action on?

as far as what it does, i think that staying on the screen the user is on
is key unless they want to go somewhere else, so a popup is ideal. maybe
you could make the click action open an overlay menu with options to
"Delete bookmark" and "View in Bookmarks menu", where if they use that link
to the bookmarks menu, it shows all bookmarks for all files, but the one
they used to get there is highlighted somehow, so they know which one it
was in case their names aren't descriptive enough? I'm not sure what
restrictions you need to work within using these frameworks, but i think
the combination of color cues and a popup menu could help. plus, if you
need to add more options for bookmarks to the popup, you've already got it
in place so it's just a matter of adding things to it (perhaps a "Rename
bookmark" option).

**Comment by williamkray** [comment]
one more addition to this request would be that if a file is a podcast, then pausing would automatically bookmark. i've already lost my place after leaving it paused for more than 10 minutes :)

**Comment by dough10** [comment]
I forgot about that. I am removing the timer (thought i already had) With the timer removed do you still feel that would be needed?

**Comment by williamkray** [comment]
I think auto-bookmarking would still be good, in case the app crashes (hasn't happened to me yet) or chrome crashes, i restart my computer, or do something else to cause the app to close without me creating a bookmark. most podcasting apps tend to auto-save your position, so this wouldn't be unusual behavior.

if you're concerned with overwriting old bookmarks, you could make it a setting, but i think in the context of podcasts, people will probably be alright with overwriting old progress automatically. you could also probably just delete the bookmark if the file is 98% completed (or rather, the bookmark that WOULD be created is past the 98% threshold), but that starts getting more advanced, and you may want to play with that behavior more before implementing.

**Comment by dough10** [comment]
I am not really concerned about overwriting bookmarks i actually feel it would greatly improve  improve my coding experience. (I can not count the times I have really been into something and lost my spot cause I had to restart the app to see changes) I guess I could still make a switch to turn off / on. 

I have the player now creating a bookmark about every 1 min of play. it will not start till about 2 min mark of the podcast. It also saves them with a comment that makes it easier to know what you are playing back if using the bookmark menu. "title @ time" format. I am going to change all default bookmark comments to match that format also. 

i need to set up the playback option for regular files to complete the feature but it is getting close. 

Oh bookmark indicator i set the color to red. i think the color does help bring attention to it having a action.

**Comment by dough10** [comment]
Ok i feel like the feature is pretty complete. I will let it ride a day or two to look for bugs and feedback before I push it.

**Comment by williamkray** [comment]
i just pulled down the latest code, and it seems to be working except the auto-generated bookmarks during a podcast. i thought that was working yesterday, so perhaps something got overwritten.

i'm listening to TWiT and skipped ahead to about 40 minutes in. listened for a few minutes, checked and found no bookmarks. created a manual bookmark, listened for a few minutes, checked, and the bookmark is still set for when i manually created it.

**Comment by dough10** [comment]
I have played around with this for a few days and I feel like it is really so close but just not quite there. Currently when playing back a album with a bookmark you have to open the album details to resume a bookmark and then you have to manually add anything after it. I am going to work on function that will feel like that current system but when clicking the big play button on the album art. Clicking start from bookmark  will start album playback from the bookmark and add anything that follows it to the play queue. This might be kind of complicated and take a few day to get correct. The feature feels incomplete / broken for albums in the current state.  (I noticed this streaming a audiobook and would never be noticed if chapters / tracks are not longer then 20 mins.)

**Comment by dough10** [comment]
I feel really good about this feature and 0.2.6 in general. I plan to upload tomorrow (Sunday) Thanks for all the input also I <3 the icon and I really appreciate you making it.

**Comment by williamkray** [comment]
No problem! I try and help projects I like, in any way I can. I don't know
enough about html/css/javascript to be helpful in that arena, but I'll do
what I can with what I've got :)

--Sent from my mobile
