### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by williamkray** [dough10/PolySonic#40]
i've designed a more unique icon to represent polysonic, but since it's very subjective, i won't do a whole pull-request and all that jazz. i'll just give you a link to it, and you are welcome to use it if you would like. https://www.kray.ca/owncloud/index.php/s/6emvjVQEirrUIw4

i have a script that auto-generated some sizes more specific to android, but feel free to resize or modify from the original SVG. I used Inkscape to make it, so it should be fully compatible.

**Comment by dough10** [comment]
Thank you sir.. I am not a very good designer I don't think and I have been wanting to update the icon for a few versions now. (spent a total of about 3 mins making the current one and most of that time was spent trying to find a template) i just haven't wanted to put in the time. i have set the icon to be pushed in 0.2.6.
