### ISSUE TITLE
API version and authentication

### ISSUE THREAD

**Issue by spl0k** [dough10/PolySonic#43]
PolySonic seems to make API calls with conflicting parameters.
By looking at the URLs it constructs, we can notice the following:
- the first request (`/rest/ping.view`, to login) uses the `u`and `p` parameters for authentication, with the password sent as clear text, and `v` with a value of *1.11.0*
- subsequent requests use the version sent back by the server for `v` and the `u`, `t` and `s` parameters for authentication, regardless of the API version supported by the server.

First of all, because PolySonic uses of those `t` and `s` parameters for authentication it should advertise itself as using API version *1.13.0* since they were introduced with this version.

Next, if the server responds to the first ping with a version inferior to *1.13.0*, I suggest PolySonic should fallback to using the `p` parameter for authentication and restrict the API calls it can make to the ones that were available with this specific version.
Not doing so would cause servers using earlier versions of the API (such as my implementation: [Supysonic](https://github.com/spl0k/supysonic), using version *1.8.0*) to not be able to work with PolySonic. This can also be the cause of the infinite spinner mentioned in #37.

**Comment by dough10** [comment]
What version is being returned from the server? The way the url is constructed atm by polysonic  it checks to see if the version is greater then 1.12.0. (thinking from the api documentation that the api version always ended in .0) 

if (parseFloat(app.version, 10) <= 1.12) {
} else {
  // uses new autentication
}


0.2.7 i will fix this to check for the proper api version and to only use the new values 1.13.0 and above.

**Comment by spl0k** [comment]
My server returns version *1.8.0*.
These are the first two requests sent by PolySonic:
```
127.0.0.1 - - [15/Aug/2015 18:15:00] "GET /rest/ping.view?u=spl0k&v=1.11.0&c=PolySonic&f=json&p=enc%3A6c6f6c HTTP/1.1" 200 -
127.0.0.1 - - [15/Aug/2015 18:15:00] "GET /rest/getMusicFolders.view?u=spl0k&v=1.8.0&c=PolySonic&f=json&s=uNUbLrFxY6lX48zM&t=e785258e83c71c87d6a7689c8cb64328 HTTP/1.1" 401 -
```

The API had some versions ending with something other than *.0* by the way (ie *1.10.1* or *1.10.2*)

**Comment by dough10** [comment]
This has to be something with the way I am trying to parse the value returned from the server. Polysonic isn't intended to work on any api version lower then 1.11.0. (it isn't strictly enforced but official subsonic lacked the proper headers before 1.10.?  i think.) I will work on this some over the weekend. I am sure there is a better way for me to parse the api version returned and throw errors accordingly.

How does your api version match up to the official subsonic version number? Is your 1.8.0 equal to 1.12.0?

**Comment by spl0k** [comment]
It's the official API version numbering, so 1.8.0 is 1.8.0.
It just lacks the share, video, podcast and jukebox features.

**Comment by dough10** [comment]
parseFloat('1.8.0') > parseFloat('1.13.0') = true  Is the root of my issue. 

parseFloat('1.8.0') = 1.8

parseFloat('1.13.0') = 1.13

This did not come up before as i was not thinking about supporting versions lower then 1.10.0. The issue is for sure the method i was checking to see if i could use the new authentication. 

0.2.7 branch the new authentication is a settings menu option and off by default.  The switch will still show for anyone on api version 1.8.0 until i figure out how to quickly check < > of the version returned from server.

**Comment by spl0k** [comment]
https://gist.github.com/TheDistantSea/8021359 might help you.

**Comment by dough10** [comment]
That function is really a big help. Thanks
