### ISSUE TITLE
Shuffle issues

### ISSUE THREAD

**Issue by LeonvanHeerden** [dough10/PolySonic#44]
I have found 2 issues so far:
1. When you click the Genre Dropdown, the list of Genre are not sorted. 
2. I have tried the default 50  songs and 40 Songs, but i only get a couple of songs returned every time. Between 19 and 6 so far.

**Comment by dough10** [comment]
At the moment the genres dropdown is sorted by the genre with most results at top and least at the bottom the same way that api call lists them. It may be better to in future releases sort them alphabetically or maybe display the # or results also so the sorting makes more sense.

As far the number of results returned if selecting a genre with say 20 tracks in it and i have max results set to 50 i will still only get 20 results. Again maybe displaying the # of results would help this more more sense to the user.

This api call seems kind of strange. I guess there are more things I could do client side to make things  feel right. Maybe when selecting a genre I could set the # of results to return to a number closer to the # of results in the genre?

**Comment by LeonvanHeerden** [comment]
Thanks for the feed back. 
I did test this with Genre that i know has hundreds of songs. So I don't know what the issues is. I will try and check the Subsonic logs for more clues.
