### ISSUE TITLE
The app sto the play when minimized for some minutes

### ISSUE THREAD

**Issue by openaspace** [dough10/PolySonic#46]
Hello, 
I see that the app stop the play when is minimized and the last track finish.

There is some wrong in my configuration?

thanks.

**Comment by dough10** [comment]
Nothing in your config. I have noticed this also. It started a after a chrome update a while back and I( am looking for a fix.

**Comment by dough10** [comment]
I have been looking at this issue more of late.  It seems this started when the chrome update that stops auto play on tabs that do not have focus.  Will post back here if I am able to find anymore info on this issue.

**Comment by nkean** [comment]
Might have already found this, but disabling this flags reverts the pausing of background content.

chrome://flags/#disable-gesture-requirement-for-media-playback

**Comment by FoxBJK** [comment]
I used to see this problem, but recently I've noticed that everything plays just fine while the app is in the background or minimized. Did Chrome fix this?

I do not have chrome://flags/#disable-gesture-requirement-for-media-playback turned on

**Comment by dough10** [comment]
I hope so. I looked at some chrome release notes but didn't seen anything about it.  I have the flag toggled on my chrome installs so I have not noticed a difference.

**Comment by FoxBJK** [comment]
Just posting for the record that this is definitely fixed now. Have tested on Chrome and Chrome Dev with both Windows and Ubuntu, and the next tracks are playing no problem. The #disable-gesture-requirement-for-media-playback setting is on it's default (enabled? not sure)

**Comment by FoxBJK** [comment]
This started happening for me again with Chrome v.50

**Comment by FoxBJK** [comment]
Wanted to check on this, see if this is replicating for anyone else. I've been seeing this issue for awhile since the bug was closed

**Comment by dough10** [comment]
I have noticed this happening again. I have started a Polymer 1+ version and I will be looking into a lot of the known issues as i refactor the code.  Development on the new version will be a slow process cause I am changing jobs and just do not have as much time to dedicate to it.
