### ISSUE TITLE
API token auth doesn't work with LDAP authentication

### ISSUE THREAD

**Issue by williamkray** [dough10/PolySonic#50]
This is an issue with the API handling of the tokenization for LDAP users (any apps that use token credentials via the API will simply respond with "Bad username or password"). As such, I'm unable to log in via the polysonic app. Using token auth should either be optional or reverted until this breaking change is fixed on the server side.

I don't know where I should submit a bug report for the server software, if anyone has ideas please let me know.

**Comment by dough10** [comment]
Thanks for letting me know about this. I will work on something to get this fixed as soon as I can. The Subsonic api form is https://groups.google.com/forum/#!forum/subsonic-app-developers

**Comment by dough10** [comment]
There is already a post about the issue on that forum. https://groups.google.com/forum/#!topic/subsonic-app-developers/1z-p3x7DqmU Doesn't look like it has gotten any attention from devs.

**Comment by dough10** [comment]
Quickest and easiest solution i can think of is a toggle on login dialog that allows the user to disable token auth. I have a patch ready with that change I can push soon. I just want to test some changes a bit. I have rushed my last couple uploads and had to upload again directly after. 

https://github.com/dough10/PolySonic/tree/0.2.7.3

**Comment by williamkray** [comment]
no rush, push it when it's ready. ldap users appear to be the minority, since there isn't a lot of complaining about this issue :)
