### ISSUE TITLE
unable to launch app a second time

### ISSUE THREAD

**Issue by williamkray** [dough10/PolySonic#52]
my subsonic server uses LDAP authentication, so i disable md5 auth (thanks for that!)

everything works when i first install and log into the app.

i close the app, and re-open it, and i just get the spinning circle. if i uninstall and reinstall the app and enter my credentials again fresh, everything works fine.

a local account does not demonstrate this behavior, with md5 auth both enabled and disabled everything seems to work fine.

let me know if you'd like an LDAP account on my server to test behavior, if you're unable to replicate the issue.

**Comment by dough10** [comment]
This is interesting.  Looks like I have something wrong in the load function.  A temp account on your server would help a lot.  My nas has crashed so my subsonic server isn't online for testing and would save me the time of spinning up a virtual machine.  If you want to shoot the account info to my email I will look at this as soon as I can.

Thanks 


Doughten.jimi@gmail.com

**Comment by dough10** [comment]
Kind of silly mistake loading settings from local storage causing this issue. When  loading settings I am  setting the variable that enables / disables md5 authentication like this 

```javascript
app.md5Auth = localStorage.md5Auth || true;
```

I wasn't thinking that if localStorage.md5Auth is false then it will default back to true. (feeling pretty dumb atm) Anyway fix inc.

**Comment by williamkray** [comment]
haha, glad i found the bug! i'll keep those user accounts in place for
further testing in the future, they've come in handy with a couple other
developers as well ;)
