### ISSUE TITLE
Media Control Keys?

### ISSUE THREAD

**Issue by nkean** [dough10/PolySonic#53]
Any plans to include support for media controls?  There are a couple of extensions that offer APIs you can add to your chrome apps.  

Key Socket Media Keys
Media Keys by Sway.fm
Streamkeys

Would love to have this feature!

**Comment by dough10** [comment]
I have thought about it but my keyboard doesn't have media keys for me to test with. I guess i need software to emulate them. do you know of any?

**Comment by nkean** [comment]
They're hooking into chrome's built in keyboard mapping feature if I understand it correctly.  Let me know if you want any help testing it.  I've got media controls on a few machines, but I assume if it works on one, it will work on all.

**Comment by dough10** [comment]
yeah Ill be using the chrome.commands API. I just didn't realize i can set default to media keys in code then rebind to what ever from a interface. This will not be bad to implement a hour or so and maybe a little time for testing.

**Comment by dough10** [comment]
Media keys should be working in the 0.2.7.5 build I just posted. https://github.com/dough10/PolySonic/tree/0.2.7.5  

If you want to test you can just download the build folder & install into chrome in dev mode. 

I will push to the chrome web store later tomorrow or so if no issues come up.

Thanks for that feedback & I hope you enjoy using the app

**Comment by nkean** [comment]
Everything is working great on my end.  Thanks for the quick response!
