### ISSUE TITLE
Play/Pause button on Now Playing screen

### ISSUE THREAD

**Issue by nkean** [dough10/PolySonic#54]
The Play/Pause button graphic at the bottom of the Now Playing screen does not change state.  Clicking pauses the audio, but the graphic stays as the pause icon.  I assume it is meant to work the same as the small bar when browsing other media.

**Comment by dough10** [comment]
I looked @ this last night before i pushed to web store but i wasn't able to duplicate it.

Thanks for bringing it to my attention and i will keep a eye on it to see what i can do to make it always work as expected.

Thanks again
