### ISSUE TITLE
Flac playback isn't working

### ISSUE THREAD

**Issue by IvanVas** [dough10/PolySonic#56]
Flac playback isn't working. Tried both with transcoding on and off.
Works on Android client.

**Comment by dough10** [comment]
Thanks for the heads up. I will look into this so far I have not had issues with flac playback from my server. HTML5 audio can not directly playback flac audio so  ATM all media queries ask for a transcoded version by default @ 320 kbps unless changed in the setting menu. The only files that are requested in raw format are podcasts as transcoding those files causes them to stop playback @ track markers. 

If you would like you could make a temp account on your server for me to test flac playback to PolySonic with. If interested email the details to doughten.jimi@gmail.com and i will look into it ASAP.

HTML5 audio supported formats http://hpr.dogphilosophy.net/test/

so for  now all flac files should be transcoded to be played back in PolySonic.

Thanks for the feedback.

**Comment by IvanVas** [comment]
Thanks for the quick reaction.

Works on Android (DSub client), doesn't work on Mac 64bit/Chrome + PolySonic
maling details now...
