### ISSUE TITLE
Slow album art download

### ISSUE THREAD

**Issue by poxin13** [dough10/PolySonic#57]
I've connected via my local network to my subsonic server. The album art takes roughly 3-4 minutes to load for about 50 artists. The art has to reload every time you click on a new list to sort.

This is using the chrome web store app, the delay makes it pretty unusable.

**Comment by dough10** [comment]
What are your system specs? 

PolySonic doesn't download the images every time. It downloads them once and stores them in indexeddb for later use. On page / sort change if fetches the image from indexeddb and displays it to the user. So the delay you are seeing is indexeddb performance and not download performance. 

Lower end machines do struggle with indexeddb especially  when fetching a large # of items @ a time. Reducing the size of the app will reduce the # of indexeddb request allowing images to load a little faster.  I see this on my  chromebook HP 11. I will look into faster methods for storing / fetching images. 

Thanks for your feedback.

**Comment by poxin13** [comment]
Ah, okay. It's a Toshiba CB2 with 4gb. Seems okay in the web app or using dsub on android so I didn't figure it was my server.

**Comment by dough10** [comment]
I am thinking the way for me to get the images to the screen the fastest would be to save the image to the filesystem and save its location in indexed db. Instead of saving the image blob It's self to indexeddb. I feel like this would provide better performance across all machines.  I will experiment and do a little more research then update here with my findings.

**Comment by poxin13** [comment]
That would work for me. A plus would be to specify storage location so you could use an attached SD card or USB. Chromebooks unfortunately have precious little space.

**Comment by poxin13** [comment]
Perhaps an option to toggle album art off all together for slower devices?

**Comment by dough10** [comment]
i think that would be possible with the list mode i am doing in 0.2.6. A art off mode would default the display mode to list and disable the art i have on the left of the list item now. (attaching screenshot for reference)  It would have to disable the icon in the top right as well. Art for playing content would stay as is. This type of feature would be a version or two away as there would be a lot of figure out.

![list mode](https://cloud.githubusercontent.com/assets/7014926/12225264/5871f386-b7cc-11e5-86be-a6488873456f.png)

**Comment by dough10** [comment]
So the method i am going to use for caching images in 0.2.6 will be to use the filesystem api and only use indexeddb for saving the album art color palettes at this time. (I may save those in regular localstorage in the future) 

Using this method has reduced the time to get the first piece of art to the screen from 600+ ms to just under 40 ms on my desktop. This should greatly affect the feel of the list and enhance scrolling performance. It may still be a week or two before this change gets to the web store as this version is pretty much in pieces ATM.
