### ISSUE TITLE
"Folder" picker assigns an id of 0 to both "All Folders" and the first folder in the list. 

### ISSUE THREAD

**Issue by jakebriggs** [dough10/PolySonic#58]
In the "Folder" picker, it appears that the drop down assigns an id of 0 to both "All Folders" and the first folder in the list. Picking either "All Folders" or the first folder in the list always results in "All Folders" being the chosen option, rather than the actual folder picked.

I tried to fix it, but the build instructions didn't work for me so I am unable to provide a fix :/

In https://github.com/dough10/PolySonic/blob/master/src/index.html#L64 we have this bit of code:

                    <core-menu class="menu" selected="{{folder}}" valueattr="i">
                      <paper-item i="0" on-tap="{{setFolder}}">{{folderSelectorLabel}}</paper-item>
                      <template repeat="{{mediaFolders}}">
                        <paper-item i="{{id}}" on-tap="{{setFolder}}">{{name}}</paper-item>
                      </template>
                    </core-menu>

It assigns the first element - the "All Folders" element - an id of 0, with on-tap set to setFolder. I think the repeated 

                    <paper-item i="{{id}}" on-tap="{{setFolder}}">{{name}}</paper-item>
  
a couple of lines down repeats over mediaFolders and mediaFolders is zero indexed. If I look at the rendered code in the debugger, we see that the two first items in that list do indeed have the same id - 0

**Comment by dough10** [comment]
I will look @ this asap. 

what step of dev environment setup was the issue?  I will look back @ the build setup process and see what i can fix there as well.

**Comment by jakebriggs** [comment]
I clone from master, and do the other steps listed, but when I run grunt I just get:

```
jake@beastie:~/projects/PolySonic$ grunt
Running "vulcanize:default" (vulcanize) task
Warning: ENOENT: no such file or directory, open '/home/jake/projects/PolySonic/src/bower_components/x-notification/x-notification.js' Use --force to continue.

Aborted due to warnings.
jake@beastie:~/projects/PolySonic$ grunt --force
Running "vulcanize:default" (vulcanize) task
Warning: ENOENT: no such file or directory, open '/home/jake/projects/PolySonic/src/bower_components/x-notification/x-notification.js' Used --force, continuing.

Running "uglify:build" (uglify) task
>> Destination build/PolySonic.js not written because src files were empty.

Running "copy:main" (copy) task
Warning: Unable to read "src/PolySonic.html" file (Error code: ENOENT). Used --force, continuing.

Done, but with warnings.
jake@beastie:~/projects/PolySonic$
```

I intended to remove the uglify task, so I could debug it easier in the chrome debugger. I think perhaps the  `bower install` step that doesn't work, since the first issue about a missing file `bower_components/x-notification/x-notification.js`

**Comment by dough10** [comment]
oh i am using a polymer element that isn't versioned on polymer 0.5. https://github.com/1000ch/x-notification/tree/db1c80deb5ce787e19d413177c91024e3da7ed61 is the newest version that will work. I forgot about that. I will update the recent version with this included in my package. my current working version is app-globals. I am about 70% of the way through refactoring the code.

**Comment by dough10** [comment]
I have a fix by changing the first child of the dropdown to have a i value of none as opposed to 0. That should fix it for future releases. Thanks for the help. Sorry about the nightmare that is some of my code. Attempting to fix that in 0.2.8 https://github.com/dough10/PolySonic/tree/app-globals

**Comment by jakebriggs** [comment]
No worries, it looks fine to me :)

Sorry I couldn't get the build going. Can't wait to get the fix

**Comment by jakebriggs** [comment]
I pulled from app-globals, and it all seems to be working good now :D

**Comment by dough10** [comment]
Great news. That version should be ready for release in a week or so. I feel like it is close to ready just wanna make sure i don't leave any obvious bugs in. 

Thanks again for the feedback.

**Comment by jakebriggs** [comment]
No problem :)
