### ISSUE TITLE
Multiple server profiles?

### ISSUE THREAD

**Issue by nkean** [dough10/PolySonic#59]
Would it be possible to setup profiles for multiple servers?  I use PolySonic at home and away and have to change the server settings each time I change location.  It would be awesome if I could have a profile for home and away so that I could have them already set and switch between those setting with one click.

**Comment by dough10** [comment]
I will look into it and see how others are doing this. This would be something for version 0.2.9 as 0.2.8 is almost ready for release. I think maybe save the servers details in synced storage and save the currently used server in non synced / local storage. That would keep you from having to change every time you change locations.  Then maybe a error connecting dialog that would allow for switching servers if network error occurs. Any input on how you would like to see this implemented in the interface would be great.  This would be a great enhancement but it will take some thought to get the interface right.

**Comment by dough10** [comment]
Anyone got input on what would be the desired behavior for saving a config for a server that can not currently be connected to? 

options i have in mind
1 error dialog

2 error dialog with option to save anyway

3 save anyway


In the current build all configs are checked to make sure a connection can be made before it can be saved.

**Comment by dough10** [comment]
Added in version 0.2.9
