### ISSUE TITLE
Blank Side Menu

### ISSUE THREAD

**Issue by nkean** [dough10/PolySonic#62]
After the newest update, the side menu only shows the search bar.  The rest of the menu is transparent.

**Comment by dough10** [comment]
This is strange.  I am not sure what change could do that. Try reinstall.

**Comment by dough10** [comment]
Is this still happening?

**Comment by nkean** [comment]
Sorry for my late response.  This is still an issue.  I've reinstalled a few times now but still no success fixing this.  I'm running the dev channel of chrome on OS X 10.11.3

**Comment by dough10** [comment]
I have just upgraded to dev channel and now see what you are talking about. I have tried to debug a little bit. it looks like either I or the old version of Polymer I am using are using some css selectors that may have been removed.

**Comment by dough10** [comment]
I have found a fix that works for now. For whatever reason the app drawer content has a height of 0 on dev channel. Forcing to height 100% allows you to see the drawer content again. I will get a fix out to the web store soon.

**Comment by dough10** [comment]
I just pushed a fix to the chrome web store.
