### ISSUE TITLE
'spinning loader' stuck

### ISSUE THREAD

**Issue by acroyear** [dough10/PolySonic#66]
With 0.2.9, I can't get passed the config login page. i get it, check my settings, connect-and-save, and then the spinner just spins seemingly forever. with a debugger attached to it, i'm not even seeing the network attempt to connect to anything beyond a follow-up 'ping'.

i haven't tried uninstalling it to wipe out my data then re-installing. at least, not yet.

**Comment by dough10** [comment]
I wil look into this soon. I am already finding some other issues with the config system.

**Comment by dough10** [comment]
When this happens are you creating a config from scratch or upgrading settings from a existing install?

**Comment by acroyear** [comment]
I had a configuration in there when I started it up after the 0.2.9 update. The error happens both in loading that one and in trying to create a new one.

**Comment by dough10** [comment]
I have not been able to make this happen for me. Maybe try clearing the app local storage settings. Run in console  `chrome.storage.sync.clear()` and for local settings `chrome.storage.local.clear()` then reload the app.

**Comment by dough10** [comment]
I am thinking this is connected to a issues where when changing configs I was trying to remove old image data but was actually attempting to delete a folder that had not been created yet and was not returning the error to console. I have changed the order that things happen for this function and it seems to have fixed that issue. I will push to web store soon

**Comment by dough10** [comment]
i am going to assume that the fixes in 0.2.9.1 fixed this. Please re open if that isn't the case
