### ISSUE TITLE
Feature Request - Delete All Bookmarks

### ISSUE THREAD

**Issue by FoxBJK** [dough10/PolySonic#68]
Throughout the course of using this app, a lot of bookmarks have been set for all my podcasts. Most of the bookmarks I have are no longer needed, but the UI for removing more than 1 bookmark is very tedious and frustrating. Can you add a button to remove all bookmarks? If not, can you change the UI so that it doesn't close out the whole Bookmarks window after deleting 1?

Thanks!

**Comment by dough10** [comment]
Yes I think a remove all button with a confirmation dialog would work. I could put it in a "three dot" / more options dropdown.

When deleting a bookmark the window needs to close when the confirmation dialog opens cause sometimes the conformation dialog will not be on top. After deleting the bookmark window should reopen. If it isn't that is a bug i need to look into.

**Comment by dough10** [comment]
This option was added in 0.2.9.2 and bookmark page bug that caused it not to re open after deleting a bookmark has been fixed.
