### ISSUE TITLE
Feature Request - Play/Pause using space bar

### ISSUE THREAD

**Issue by FoxBJK** [dough10/PolySonic#70]
I'm not sure what you officially call it, but when you're in the full player view (i.e. the attached), I can only pause the thing I'm listening to via the actual button. If possible, can you bind space bar to play/pause? Minor detail, but would be so nice to have.

Thanks for all you do!

**Comment by dough10** [comment]
This will not be any issue to include. I added a version 0.2.9.3 with the feature.  I will push that to web store in a day or so. 

Thanks.
