### ISSUE TITLE
App won't launch

### ISSUE THREAD

**Issue by h3man1** [dough10/PolySonic#76]
Title says it all. When I open the app it's stuck at the spinning wheel screen.

**Comment by dough10** [comment]
Sorry this app hasn't been in active development in @ least 3 years. At this point this app would require a ground up rewrite to get up to date with current Polymer version.

**Comment by h3man1** [comment]
yep, forgot to look at the dates. sorry to hear about current state as it looks like the kind of app I am  searching for right now.
